<?php
/**
 * Страница "Список стиков".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>List of debug info sticks</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>The list displays all debug information sticks.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Дата.</b> Date and time the user's request was executed;</li>
        <li><b>IP address.</b> IP address of the user who made the request;</li>
        <li><b>Stick ID.</b> Stick Identifier;</li>
        <li><b>Memory.</b> Memory allocated to receive response from user in MB;</li>
        <li><b>Module / ID.</b> Module Identifier;</li>
        <li><b>Module / Name.</b> Module name;</li>
        <li><b>Controller / Name.</b> Module controller name;</li>
        <li><b>Controller / Action.</b> Action of the module controller;</li>
        <li><b>Controller / ID.</b> The identifier of the controller action or record on which the action was performed;</li>
        <li><b>Request / OS.</b> The name and version of the operating system of the user who performed the action;</li>
        <li><b>Request / Browser.</b> The name and version of the browser of the user who performed the action;</li>
        <li><b>Request / Route.</b> Route obtained from user request;</li>
        <li><b>Request / Метод.</b> Method for receiving a request from a user;</li>
        <li><b>Request / AJAX.</b> Was the request made using AJAX;</li>
        <li><b>Request / Status.</b> The response code for the user's request execution.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Clear.</b> Delete all debug information sticks;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refresh the list of sticks;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands and collapses the Navigation Panel to display information about the selected stick entry;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Shows the help window for the current list.;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Shows the form for searching records in the list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Filter.</b> Shows the form for filtering records in a list.</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-debug-active.svg' ?>" /> <b>User action recording.</b> Shows the logging settings window;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-state.svg' ?>" /> <b>State.</b> Shows a window to view the user's current state;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-server-info.svg' ?>" /> <b>Configuration.</b> Shows a panel for viewing the server configuration.</li>
    </ul>
</article>